#!/bin/bash

CID_PATH=/var/change_ip_detector/



mkdir -p $CID_PATH
touch $CID_PATH/addresse_old

wget http://www.kamikase.info/tools/adresse.php -O $CID_PATH/addresse_tmp 2>/dev/null 1>/dev/null


ADDRESSE_TMP=$(cat $CID_PATH/addresse_tmp)
ADDRESSE_OLD=$(cat $CID_PATH/addresse_old)


if [ "$ADDRESSE_TMP" != "$ADDRESSE_OLD" ] ;  then
    echo "new address detected: $ADDRESSE_TMP"
    cp $CID_PATH/addresse_tmp $CID_PATH/addresse_old
fi




