#!/bin/bash

###############################################################################
MAIL="cmoidavid@gmail.com,jxing33@gmail.com"
URL=http://www.kamikase.info/tools/adresse.php
TITLE="Asrock ION 330"
PREFIX="/home/dmoreau/src/change_ip_detector/"
###############################################################################



# Program parameters
NAME=ip_change_detector
VERSION=1.0

# Execution parameters
CID_PATH=$PREFIX/var/
OLD_PATH=$CID_PATH/old_address
TMP_PATH=$CID_PATH/tmp_address
LOG_PATH=$CID_PATH/$NAME.log



function log {
	echo "$(date +%d-%m-%y) $(date +%H:%M) $1" >> $LOG_PATH
}



function log_and_mail {
	echo "$(date +%d-%m-%y) $(date +%H:%M) $1" >> $LOG_PATH
	echo $1 | mail -s "$TITLE" -t "$MAIL"
}


mkdir -p $CID_PATH


if [ ! -f $OLD_PATH ]
then
	log "Create $OLD_PATH"
	echo "0.0.0.0" >  $OLD_PATH
fi

if [ ! -f $TMP_PATH ]
then
	log "Create $TMP_PATH"
	echo "0.0.0.0" >  $TMP_PATH
fi


WGET_LOG=$(wget $URL -O $TMP_PATH 2>/dev/null)
if [ $? -ne 0 ]
then
	log_and_mail "wget failed: $WGET_LOG"
	exit 1
fi

ADDRESS_TMP=$(cat $TMP_PATH)
ADDRESS_OLD=$(cat $OLD_PATH)


if [ "$ADDRESS_TMP" != "$ADDRESS_OLD" ]
then
	log_and_mail "detected: $ADDRESS_TMP"
	cp $TMP_PATH $OLD_PATH
else
	log "no change $ADDRESS_TMP"
fi



exit 0
